services:
    webserver:
        image: nginx:${NGINX_VERSION:-latest}
        container_name: webserver
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./nginx/conf/:/etc/nginx/conf.d/:ro
            - ${BKP_DIR}/certs/www/:/var/www/certbot/:ro
            - ${BKP_DIR}/certs/conf/:/etc/nginx/ssl/:ro
            - ${WWW_DIR}:/www/data/:ro
    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        volumes:
            - ${BKP_DIR}/certs/www/:/var/www/certbot/:rw
            - ${BKP_DIR}/certs/conf/:/etc/letsencrypt/:rw
